# Generated by Django 5.0.7 on 2024-11-10 02:25

import bloger.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django_ckeditor_5.fields import CKEditor5Field  # Import CKEditor 5 field

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the category name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the category')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='bloger_cate_slug_1617e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title (minimum 5 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle for your post', max_length=200)),
                # Update body to use CKEditor5Field for CKEditor 5 integration
                ('body', CKEditor5Field('Body', help_text='Main content of your post (minimum 100 characters)', validators=[django.core.validators.MinLengthValidator(100)])),
                ('image', models.ImageField(blank=True, help_text='Featured image for the post', null=True, upload_to='blog_images/%Y/%m/')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the title', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('likes', models.ManyToManyField(blank=True, related_name='blog_post_likes', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='bloger.category')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Your comment (minimum 5 characters)', validators=[django.core.validators.MinLengthValidator(5)])),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='bloger.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bloger.blogpost')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_on', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to='bloger.blogpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post View',
                'verbose_name_plural': 'Post Views',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(help_text='A brief introduction (max 100 words)', validators=[bloger.models.validate_bio_length])),
                ('profile_picture', models.ImageField(default='defaults/default_profile.png', help_text='Upload a profile picture', upload_to='profile_img/%Y/%m/')),
                ('career', models.CharField(blank=True, help_text='Your current profession or career path', max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, help_text='Your birth date (optional)', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Your LinkedIn profile URL', null=True, validators=[django.core.validators.URLValidator()])),
                ('education', models.JSONField(blank=True, default=list, help_text='List of educational qualifications', null=True)),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of professional skills', null=True)),
                ('projects', models.JSONField(blank=True, default=list, help_text='List of projects', null=True)),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='Professional recommendations', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='bloger_blog_slug_7aa999_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', 'created_on'], name='bloger_blog_status_3c0e49_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['writer'], name='bloger_blog_writer__023b36_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['category'], name='bloger_blog_categor_043d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_on'], name='bloger_comm_post_id_471218_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['commenter'], name='bloger_comm_comment_22d120_idx'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['user', 'post'], name='bloger_post_user_id_2ff98e_idx'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['viewed_on'], name='bloger_post_viewed__7a6b12_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='bloger_user_user_id_ea57cf_idx'),
        ),
    ]
