# Generated by Django 5.0.7 on 2024-11-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
