# Generated by Django 5.0.7 on 2024-11-14 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0002_blogpost_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='defaults/default_cover.png', help_text='Upload a cover photo', null=True, upload_to='cover_img/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Your current location (e.g., city, country)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, help_text='A link to your personal website or portfolio', null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
