# Generated by Django 5.0.7 on 2024-11-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0003_userprofile_cover_photo_userprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
