# Generated by Django 4.1.5 on 2023-06-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0003_remove_blog_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='image',
            field=models.ImageField(default='null', upload_to='blog_images'),
        ),
    ]
