# Generated by Django 5.0.7 on 2024-11-15 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0004_userprofile_last_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_likers', to='bloger.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Like',
                'verbose_name_plural': 'Profile Likes',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='likes',
            field=models.ManyToManyField(blank=True, help_text='Users who like this profile', related_name='liked_profiles', through='bloger.ProfileLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follows', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followers', to='bloger.userprofile')),
            ],
            options={
                'verbose_name': 'User Follow',
                'verbose_name_plural': 'User Follows',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, help_text='Users who follow this profile', related_name='following', through='bloger.UserFollow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='profilelike',
            index=models.Index(fields=['user', 'profile'], name='bloger_prof_user_id_d9e5f7_idx'),
        ),
        migrations.AddIndex(
            model_name='profilelike',
            index=models.Index(fields=['created_at'], name='bloger_prof_created_545f6d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profilelike',
            unique_together={('user', 'profile')},
        ),
        migrations.AddIndex(
            model_name='userfollow',
            index=models.Index(fields=['follower', 'following'], name='bloger_user_followe_510a57_idx'),
        ),
        migrations.AddIndex(
            model_name='userfollow',
            index=models.Index(fields=['created_at'], name='bloger_user_created_365817_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfollow',
            unique_together={('follower', 'following')},
        ),
    ]
