# Generated by Django 5.0.7 on 2024-11-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0005_profilelike_userprofile_likes_userfollow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='work_experience',
            field=models.JSONField(blank=True, default=list, help_text='List of work experiences (e.g., job titles, companies, and dates)', null=True),
        ),
    ]
