# Generated by Django 5.0.7 on 2024-11-25 00:50

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0006_userprofile_work_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
