# Generated by Django 5.0.7 on 2025-03-12 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0007_alter_blogpost_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_address',
            field=models.TextField(blank=True, help_text='Your business address (for sellers)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_name',
            field=models.CharField(blank=True, help_text='Your business or store name (for sellers)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Your contact phone number (e.g., +999999999)', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_order_emails',
            field=models.BooleanField(default=True, help_text='Receive email notifications for new orders'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_order_whatsapp',
            field=models.BooleanField(default=True, help_text='Receive WhatsApp notifications for new orders'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_phone',
            field=models.CharField(blank=True, help_text='Your WhatsApp number for order notifications (e.g., +999999999)', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
