# Generated by Django 5.0.6 on 2024-05-14 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0008_remove_blogpost_categories_remove_blogpost_writer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blog_posts_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200),
        ),
    ]
