# Generated by Django 5.0.7 on 2025-03-14 16:47

import bloger.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0008_userprofile_business_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='A brief introduction (max 100 words)', validators=[bloger.models.validate_bio_length]),
        ),
    ]
