# Generated by Django 5.0.6 on 2024-05-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0009_blog_post_likes_alter_blog_post_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
