# Generated by Django 5.0.6 on 2024-05-15 01:12

import bloger.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0011_blog_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(validators=[bloger.models.validate_bio_length]),
        ),
    ]
