# Generated by Django 5.0.6 on 2024-05-15 02:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0013_userprofile_birthday_userprofile_career_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='likes',
            field=models.ManyToManyField(related_name='blogpost_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
