# Generated by Django 4.1.5 on 2024-05-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0015_remove_comment_image_comment_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
